### PR TITLE
Add support for PassengerDefaultUser

### PR DESCRIPTION
**Pull request by gollub**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @gollub

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mikeantonelli** [comment]
PassengerDefaultGroup defaults to the group of the user specified in PassengerDefaultUser, but if we're here, do you also want to add PassengerDefaultGroup?

https://www.phusionpassenger.com/documentation/Users%20guide%20Apache%204.0.html#PassengerDefaultGroup

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @gollub

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tas50** [comment]
It's been over 6 months since this PR was opened and without the CLA signed we can't merge it. I'm going to close it out now for lack of CLA.

**Comment by DStape** [comment]
https://github.com/chef-cookbooks/passenger_apache2/pull/56 rekindles this.

**Pull request closed without merging**
